name: Adwaita
author: nthelt
stylesheets:
  - file: main.css
    name: Base theme
    description: Minimalist and sleek. Designed to match the gnome desktop environment.
  - file: window-controls.scss
    name: Hide window controls
    description: Hide minimize and maximize; change to adwaita-style close button.
  - file: big-screen.scss
    name: Big screen
    description: Optimizes immersive mode for TVs.
  - file: blue.scss
    name: Blue accent
  - file: teal.scss
    name: Teal accent
  - file: green.scss
    name: Green accent
  - file: yellow.scss
    name: Yellow accent
  - file: orange.scss
    name: Orange accent
  - file: red.scss
    name: Red accent
  - file: pink.scss
    name: Pink accent
  - file: purple.scss
    name: Purple accent
  - file: slate.scss
    name: Slate accent
marketplaceID: 15
version: 2.0.0
